"""
Django settings for LFITWEB project.
Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import environ

# -----------------------------
# Paths
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# Env (.env)
# -----------------------------
# .env 예시:
# DEBUG=True
# SECRET_KEY=change-me
# ALLOWED_HOSTS=127.0.0.1,localhost
# WAGTAILADMIN_BASE_URL=http://127.0.0.1:8000
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# -----------------------------
# Wagtail
# -----------------------------
WAGTAIL_SITE_NAME = "LFIT"
WAGTAILADMIN_BASE_URL = env("WAGTAILADMIN_BASE_URL", default="http://127.0.0.1:8000")

# -----------------------------
# Core security & debug
# -----------------------------
SECRET_KEY = env("SECRET_KEY", default="dev-secret-key-change-me")
DEBUG = env.bool("DEBUG", default=True)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# -----------------------------
# Applications
# -----------------------------
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Wagtail
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",

    # 3rd party
    "modelcluster",
    "taggit",

    # Local apps
    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "LFITWEB.urls"

# -----------------------------
# Templates
# -----------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 프로젝트 공용 템플릿 폴더
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,  # 각 앱의 templates/ 자동 포함
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LFITWEB.wsgi.application"

# -----------------------------
# Database (cross-platform)
# -----------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -----------------------------
# Auth
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------
# I18N / TZ (env로 오버라이드 가능)
# -----------------------------
LANGUAGE_CODE = env("LANGUAGE_CODE", default="en-us")
TIME_ZONE = env("TIME_ZONE", default="UTC")
USE_I18N = True
USE_TZ = True

# -----------------------------
# Static & Media (OS 무관 경로)
# -----------------------------
STATIC_URL = "/static/"
# 프로젝트 단위 static 폴더를 쓸 경우(선택):
# BASE_DIR / "static" 디렉터리를 만들면 자동으로 사용됩니다.
STATICFILES_DIRS = [
    *( [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else [] )
]
STATIC_ROOT = BASE_DIR / "staticfiles"   # collectstatic 대상 (배포용)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -----------------------------
# Default PK
# -----------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
